components:
  schemas:
    RoleResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    
    CreateRoleBody:
      type: object
      properties:
        name:
          type: string