components:
  schemas:    
    CreateProductRequestBody:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        quantity:
          type: integer
          format: int32
        status:
          type: string
          enum:
          - available
          - sold
          - unavailable
        brand:
          type: string

    UpdateProductRequestBody:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        quantity:
          type: integer
          format: int32
        status:
          type: string
          enum:
          - unavailable
          - available
          - sold
        thumbnail:
          type: string
        brand:
          type: string
        category:
          type: string

    ProductResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        quantity:
          type: integer
          format: int32
        status:
          type: string
          enum:
          - unavailable
          - available
          - sold
        thumbnail:
          type: string
        brandId:
          type: string
          format: uuid
        categoryId:
          type: string
          format: uuid
          
